name: Deploy

on:
  workflow_run:
    workflows: [ "Build" ]
    types: [ completed ]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: live
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Deploy
        env:
          TAG: sha-${{ github.sha }}
        run: |
          # set up SSH agent and keys
          sudo apt-get update && sudo apt-get install -y openssh-client
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          ssh-keyscan -H ${{ secrets.SSH_REMOTE_HOST }} >> ~/.ssh/known_hosts

          # create a Docker context for the remote host
          docker context create remote --docker "host=ssh://${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }}"

          # Deploy the application using Docker Compose to remote host
          docker --context remote compose --project-name domain-parking --file ./deploy/docker-compose.yml up --detach --force-recreate
