name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: [ "Build" ]
    types: [ completed ]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: live
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Set up SSH agent and keys
        run: |
          apt-get update && apt-get install -y openssh-client
          mkdir -p ~/.ssh
          chmod 600 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          ssh-keyscan ${{ env.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Create Docker context
        run: |
          docker context create remote --docker "host=ssh://${{ secrets.SSH_REMOTE_USER }}@${{ env.REMOTE_HOST }}"

      - name: Deploy
        env:
          TAG: ${{ github.sha }}
        run: |
          docker --context remote compose --file ./deploy/docker-compose.yml up --detach --force-recreate
