name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: [ "Build" ]
    types: [ completed ]
    branches:
      - main

concurrency:
  group: deploy_live
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: live
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-helm@v4

      - name: Setup kubectl context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          context: ${{ secrets.KUBE_CONTEXT }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install --namespace mareshq-domain-parking \
            domain-parking ./deploy/k8s \
            --wait \
            --values ./deploy/k8s/values.production.yaml \
            --set image.tag=main-${{ github.sha }}
