name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: |
          helm lint ./deploy/k8s

      - name: Test Helm chart
        run: |
          helm template test ./deploy/k8s --values ./deploy/k8s/values.test.yaml
